[package]
name = "solana-rpc-lite"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Minimal Solana RPC crate, hand-rolled using only reqwest and serde"
repository = "https://github.com/SpriteDay/solana-rpc-lite"

[dependencies]
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"

[dev-dependencies]
clap = { version = "4.5.60", features = ["derive"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
