name: Test Suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Default tests
        run: cargo test --all-features
      - name: Integration tests requiring live Solana RPC connection
        run: cargo test --verbose -- --ignored
        env:
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          TOKEN_ACCOUNT_ADDRESS: JmHSrPX6rj1Df3pwUrQv4DW6PY2Z923XnZieAQiYWY8